/*
 * Wholesale Market
 *
 * Data related to the whole electricity market within EPEX Spot and Nord Pool hub Stock exchange operations.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ErrorErrorDetails struct {
	// unique call identifier, useful in the event of an incident
	TransactionId string `json:"transaction_id,omitempty"`
}
