/*
 * Wholesale Market
 *
 * Data related to the whole electricity market within EPEX Spot and Nord Pool hub Stock exchange operations.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelError struct {
	// short_name, error's explicit description
	Error_ string `json:"error,omitempty"`
	// long name, readable by a user
	ErrorDescription string `json:"error_description,omitempty"`
	// See the API User Guide or the FAQ on https://data.rte-france.com
	ErrorUri string `json:"error_uri,omitempty"`
	ErrorDetails *ErrorErrorDetails `json:"error_details,omitempty"`
}
