/*
 * Wholesale Market
 *
 * Data related to the whole electricity market within EPEX Spot and Nord Pool hub Stock exchange operations.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import "time"

type RespData struct {
	// Market data
	FrancePowerExchange []FrancePowerExchange `json:"france_power_exchanges,omitempty"`
}

type FrancePowerExchange struct {
	// Start date for data requested (YYYY-MM-DDThh:mm:sszzzzzz)
	StartDate time.Time `json:"start_date,omitempty"`
	// End date for requested data (YYYY-MM-DDThh:mm:sszzzzzz)
	EndDate time.Time `json:"end_date,omitempty"`
	// Date updated (YYYY-MM-DDThh:mm:sszzzzzz)
	UpdatedDate time.Time                   `json:"updated_date,omitempty"`
	Values      []ValueFrancePowerExchanges `json:"values,omitempty"`
}

type ValueFrancePowerExchanges struct {
	// Start time interval (YYYY-MM-DDThh:mm:sszzzzzz)
	StartDate time.Time `json:"start_date,omitempty"`
	// End time interval (YYYY-MM-DDThh:mm:sszzzzzz)
	EndDate time.Time `json:"end_date,omitempty"`
	// Volume of the electricity market (in MW)
	Value float32 `json:"value,omitempty"`
	// Price (in €/MWh)
	Price float32 `json:"price,omitempty"`
}

type ErrorErrorDetails struct {
	// unique call identifier, useful in the event of an incident
	TransactionId string `json:"transaction_id,omitempty"`
}

type ModelError struct {
	// short_name, error's explicit description
	Error_ string `json:"error,omitempty"`
	// long name, readable by a user
	ErrorDescription string `json:"error_description,omitempty"`
	// See the API User Guide or the FAQ on https://data.rte-france.com
	ErrorUri     string             `json:"error_uri,omitempty"`
	ErrorDetails *ErrorErrorDetails `json:"error_details,omitempty"`
}
