/*
 * Wholesale Market
 *
 * Data related to the whole electricity market within EPEX Spot and Nord Pool hub Stock exchange operations.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type FrancePowerExchanges struct {
	// Start date for data requested (YYYY-MM-DDThh:mm:sszzzzzz)
	StartDate time.Time `json:"start_date,omitempty"`
	// End date for requested data (YYYY-MM-DDThh:mm:sszzzzzz)
	EndDate time.Time `json:"end_date,omitempty"`
	// Date updated (YYYY-MM-DDThh:mm:sszzzzzz)
	UpdatedDate time.Time `json:"updated_date,omitempty"`
	Values []ValueFrancePowerExchanges `json:"values,omitempty"`
}
